# In Convolutional Neural Networks, a convolution is a linear operation that involves multiplication of weight (kernel/filter) with the input/


# It consists of 2 major components, 1. Kernel(Filter) 2. Stride

# We apply the filter and slide it across our image. This enables us to extract different features from the given input


# Stride controls the movement of the filter over the input. When it is 1, it moves 1 column at a time over the input. If it is 3, it moves 3 columns at a time over the input.

In [10]:
def cnn_filter_output(input_section, filter_value):
    # perform the multiplication of input section and the filter
    value = 0
    for i in range(len(filter_value)):
        for j in range(len(filter_value[0])):
            value += input_section[i][j] * filter_value[i][j]
    return value

# Input image
input_image = [[250.745, 261.332, 112.27 , 262.351],
               [260.302, 108.802, 139.05 , 230.709],
               [261.775, 93.73 , 166.118, 222.897],
               [259.56 , 232.038, 262.351, 228.937]]

# Filter
filter = [[1, 0], [0, 1]]

filterX, filterY = len(filter), len(filter[0])
filtered_result = []

for i in range(len(input_image) - filterX + 1):
    clm = []
    for j in range(len(input_image[0]) - filterY + 1):e
        input_section = [row[j:j+filterY] for row in input_image[i:i+filterX]]
        clm.append(cnn_filter_output(input_section, filter))
    filtered_result.append(clm)

print(filtered_result)


[[359.547, 400.382, 342.979], [354.03200000000004, 274.92, 361.947], [493.813, 356.081, 395.055]]


In [11]:
def print_image(image, title="Image"):
    print(title)
    for row in image:
        print(" ".join(f"{val:.2f}" for val in row))
    print()

print_image(input_image, "Original Image")
print_image(filtered_result, "Filtered Image")


Original Image
250.75 261.33 112.27 262.35
260.30 108.80 139.05 230.71
261.77 93.73 166.12 222.90
259.56 232.04 262.35 228.94

Filtered Image
359.55 400.38 342.98
354.03 274.92 361.95
493.81 356.08 395.06



# Dropout is a regularization technique used to prevent overfitting in neural networks. During training, dropout randomly sets a fraction of the output features of the layer to zero at each update during training time, which helps prevent overfitting by reducing the network's capacity.

# Pooling reduces the spatial dimensions of the input for the next convolutional layer. It is usually done to reduce the computation load, memory usage, and number of parameters.

In [12]:
import numpy as np

# Dropout function
def apply_dropout(input_matrix, dropout_rate):
    # Create a mask with the same shape as the input matrix
    # The mask has "dropout_rate" chance of being zero and (1 - dropout_rate) chance of being one
    mask = np.random.binomial(1, 1 - dropout_rate, size=input_matrix.shape)
    # Apply the mask to the input matrix
    dropped_out_matrix = np.multiply(input_matrix, mask)
    return dropped_out_matrix

# Max pooling function
def max_pooling(input_matrix, pool_size, stride):
    # Dimensions of the input matrix
    n_rows, n_cols = input_matrix.shape
    # Calculate the size of the output matrix
    out_rows = (n_rows - pool_size) // stride + 1
    out_cols = (n_cols - pool_size) // stride + 1
    # Create the output matrix
    pooled_matrix = np.zeros((out_rows, out_cols))
    
    # Apply max pooling
    for i in range(out_rows):
        for j in range(out_cols):
            row_start, col_start = i * stride, j * stride
            row_end, col_end = row_start + pool_size, col_start + pool_size
            window = input_matrix[row_start:row_end, col_start:col_end]
            pooled_matrix[i, j] = np.max(window)
    
    return pooled_matrix

# Example usage:
input_matrix = np.array([[1, 3, 2, 4], 
                         [5, 6, 8, 8], 
                         [9, 7, 4, 2], 
                         [3, 1, 0, 5]])

# Apply dropout with a rate of 0.5
dropout_rate = 0.5
dropped_out_matrix = apply_dropout(input_matrix, dropout_rate)

# Apply max pooling with pool size of 2 and stride of 2
pool_size = 2
stride = 2
pooled_matrix = max_pooling(input_matrix, pool_size, stride)

print("Original matrix:\n", input_matrix)
print("Matrix after dropout:\n", dropped_out_matrix)
print("Matrix after max pooling:\n", pooled_matrix)


Original matrix:
 [[1 3 2 4]
 [5 6 8 8]
 [9 7 4 2]
 [3 1 0 5]]
Matrix after dropout:
 [[0 3 0 4]
 [0 0 8 8]
 [9 7 0 2]
 [3 1 0 0]]
Matrix after max pooling:
 [[6. 8.]
 [9. 5.]]
